// Marvellous Studio visual system: dark creative-tech surfaces, orange signal color, geometric spacing, and studio-first voice.
import { useState } from "react";
import { ArrowRight, ArrowUpRight, Check, ChevronDown, Menu, X } from "lucide-react";

export const logo = "/manus-storage/marvellous-studio-logo_c13ac32e.png";
export const whatsapp = "https://wa.me/2348066253861";
export const email = "primemarvel498@gmail.com";

export const projects = [
  { id: "aurelia", name: "AURELIA", category: "Branding", type: "Brand Identity & Art Direction", description: "A realistic sample identity system for a modern lifestyle brand seeking a sophisticated and recognizable presence. It shows how typography, color, packaging, and art direction can work together across digital and physical touchpoints.", services: "Branding · Art Direction · Graphic Design", tone: "coral", image: "/manus-storage/mara-project-identity_090146d4.jpg" },
  { id: "north", name: "NORTH & CO.", category: "Web", type: "E-commerce Website Experience", description: "A realistic sample e-commerce website designed around a clean customer journey, strong product presentation, and a more confident path from discovery to purchase.", services: "Web Design · UI/UX · Development", tone: "blue", image: "/manus-storage/mara-project-digital_42683e30.jpg" },
  { id: "velora", name: "VELORA", category: "Shopify", type: "Shopify Store Redesign", description: "A realistic sample Shopify redesign showing how an outdated online store can become a cleaner, more engaging shopping experience with stronger discovery and mobile usability.", services: "Shopify · E-commerce Design · UX", tone: "orange", image: "/manus-storage/mara-project-identity_090146d4.jpg" },
  { id: "creative", name: "THE CREATIVE MIND", category: "Publishing", type: "Book Design & Publishing", description: "A realistic sample publishing package for a professional nonfiction book, covering the visual direction from cover to interior pages, editing support, typesetting, and publishing-ready preparation.", services: "Book Design · Typesetting · KDP Formatting", tone: "purple", image: "/manus-storage/mara-editorial-hero_f8fe00e3.jpg" },
  { id: "insight", name: "INSIGHT 360", category: "Analytics", type: "Business Analytics Dashboard", description: "A realistic sample business intelligence dashboard designed to turn complex business information into an accessible visual reporting experience for decision-makers.", services: "Data Analytics · Data Visualization · Dashboard Design", tone: "green", image: "/manus-storage/mara-project-digital_42683e30.jpg" },
  { id: "lumen", name: "LUMEN", category: "Content", type: "Digital Brand & Website", description: "A realistic sample digital presence bringing together brand identity, website design, and strategic content so the brand feels consistent from first impression to customer action.", services: "Branding · Web Design · Copywriting", tone: "yellow", image: "/manus-storage/mara-editorial-hero_f8fe00e3.jpg" },
];

function Header() {
  const [open, setOpen] = useState(false);
  const links = [["Home", "/"], ["About", "/about"], ["Services", "/services"], ["Pricing", "/pricing"], ["Portfolio", "/portfolio"], ["Case Studies", "/case-studies"], ["Stories", "/testimonials"], ["Contact", "/contact"]];
  return <header className="site-header"><a className="brand-lockup" href="/"><img src={logo} alt="Marvellous Studio" /></a><nav className={open ? "main-nav open" : "main-nav"}>{links.map(([label, href]) => <a href={href} key={href} onClick={() => setOpen(false)}>{label}</a>)}<a className="nav-cta" href="/contact">Start a project <ArrowUpRight size={15} /></a></nav><button className="menu-toggle" onClick={() => setOpen(!open)} aria-label={open ? "Close menu" : "Open menu"}>{open ? <X /> : <Menu />}</button></header>;
}

function Footer() { return <footer className="footer"><div><a className="footer-logo" href="/"><img src={logo} alt="Marvellous Studio" /></a><p>Creative design, digital experiences,<br />and practical solutions for moving forward.</p></div><div className="footer-links"><span className="eyebrow">Explore</span><a href="/portfolio">Portfolio</a><a href="/services">Services</a><a href="/about">About the studio</a></div><div className="footer-links"><span className="eyebrow">Say hello</span><a href={`mailto:${email}`}>{email}</a><a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp ↗</a></div><div className="footer-base"><span>© 2025 Marvellous Studio</span><span>Founded by Odola Temidayo Marvellous</span><a href="#top">Back to top ↑</a></div></footer>; }

function Layout({ children }: { children: React.ReactNode }) { return <div className="app-shell" id="top"><Header />{children}<Footer /></div>; }
function PageIntro({ kicker, title, text }: { kicker: string; title: React.ReactNode; text: string }) { return <section className="page-intro"><p className="eyebrow orange">{kicker}</p><h1>{title}</h1><p className="page-intro-text">{text}</p></section>; }
function Button({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) { return <a className={secondary ? "button button-secondary" : "button"} href={href}>{children}<ArrowUpRight size={16} /></a>; }

export function HomePage() { return <Layout><section className="home-hero"><div className="hero-content"><div className="hero-kicker"><span className="signal-dot" /> Premium creative digital studio</div><h1>We design brands, digital experiences, and solutions that <span>move businesses forward.</span></h1><p>Marvellous Studio combines graphic design, branding, web development, Shopify, publishing, content, and data analytics to help turn ideas into professional digital experiences.</p><div className="hero-buttons"><Button href="/portfolio">View our work</Button><Button href="/contact" secondary>Start a project</Button></div><div className="hero-trust">Branding <i>·</i> Web <i>·</i> Shopify <i>·</i> Publishing <i>·</i> Content <i>·</i> Analytics</div></div><div className="hero-visual"><img src="/manus-storage/mara-editorial-hero_f8fe00e3.jpg" alt="Creative studio materials arranged on a desk" /><div className="hero-visual-tag">Make it<br /><b>marvellous.</b></div><div className="hero-visual-index">01 <span>/</span> 06</div></div></section><section className="home-work section"><div className="section-top"><div><p className="eyebrow">01 / Selected work</p><h2>Built around strategy,<br /><span>creativity, and function.</span></h2></div><a className="arrow-link" href="/portfolio">See all work <ArrowRight size={18} /></a></div><div className="featured-grid">{projects.slice(0, 3).map((project) => <ProjectCard project={project} key={project.id} />)}</div></section><section className="home-statement"><p className="eyebrow orange">A multidisciplinary studio</p><h2>More than design. We build the pieces that make a business look, communicate, and <span>perform better.</span></h2><Button href="/about" secondary>Meet the studio</Button></section><section className="home-services section"><div className="section-top"><div><p className="eyebrow">02 / What we do</p><h2>One studio.<br /><span>Many ways forward.</span></h2></div><a className="arrow-link" href="/services">Explore services <ArrowRight size={18} /></a></div><div className="service-preview">{["Brand & Graphic Design", "Web Design & Development", "Shopify & E-commerce", "Book Writing & Publishing", "Copywriting & Content", "Data Analytics"].map((name, i) => <a href="/services" key={name}><span>0{i + 1}</span><strong>{name}</strong><ArrowUpRight size={17} /></a>)}</div></section><section className="home-cta"><p className="eyebrow">03 / Start a conversation</p><h2>Have an idea?<br /><span>Let&apos;s build it.</span></h2><Button href="/contact">Start a project</Button></section></Layout>; }

function ProjectCard({ project }: { project: typeof projects[number] }) { return <a className={`project-card tone-${project.tone}`} href={project.id === "velora" ? "/case-studies" : "/portfolio"}><div className="project-image"><img src={project.image} alt={`${project.name} concept project`} /><span className="concept-badge">Sample project</span><span className="project-open"><ArrowUpRight size={19} /></span></div><div className="project-card-meta"><span>{project.category}</span><h3>{project.name}</h3><p>{project.type}</p></div></a>; }

export function AboutPage() { return <Layout><PageIntro kicker="About the studio" title={<>Built for ideas that deserve to <span>move.</span></>} text="Marvellous Studio is a multidisciplinary creative digital studio focused on helping businesses, entrepreneurs, authors, and growing brands bring their ideas to life." /><section className="about-grid section"><div className="about-lead"><p className="eyebrow orange">The thinking behind the work</p><h2>Good design should not only look good. <span>It should have a purpose.</span></h2></div><div className="about-copy"><p>Marvellous Studio brings together creative design, branding, web design and development, Shopify e-commerce, copywriting, book writing and publishing, and data analytics to create solutions that are both visually engaging and useful.</p><p>Rather than treating each project as an isolated task, we look at the bigger picture — how the brand communicates, how customers experience it, and how the final product supports the client&apos;s goals.</p><div className="founder-card"><p className="eyebrow">Behind the studio</p><h3>Odola Temidayo Marvellous</h3><p>Founder & Creative Director</p><div className="founder-line" /><p>Odola helps businesses turn ideas into strong brands, digital experiences, content, and practical digital solutions.</p></div></div></section><section className="audience-band"><p className="eyebrow orange">Who we work with</p><div className="audience-list"><span>Entrepreneurs</span><span>Startups</span><span>Growing businesses</span><span>E-commerce brands</span><span>Organizations</span><span>Book authors</span></div></section></Layout>; }

export function ServicesPage() { const items = ["Brand & Graphic Design", "Web Design & Development", "Shopify & E-commerce", "Book Writing & Publishing", "Copywriting & Content", "Data Analytics"]; return <Layout><PageIntro kicker="Services" title={<>The right mix of <span>creative and practical.</span></>} text="From a first visual identity to a high-converting store or a publication ready for readers, we build the pieces that help your work travel further." /><section className="services-grid section">{items.map((name, i) => <article className="service-card" key={name}><span className="service-index">0{i + 1}</span><h2>{name}</h2><p>{["We create visual identities and communication materials that give businesses a recognizable and professional presence.", "We design responsive websites that combine strong visual presentation with intuitive navigation and functional user experiences.", "We create and redesign Shopify stores with a focus on presentation, usability, mobile responsiveness, and the customer journey.", "We help authors, entrepreneurs, educators, and organizations transform ideas into polished publications for digital and print.", "We develop clear and persuasive content that helps businesses communicate their value across every important touchpoint.", "We turn complex information into clear dashboards, visual reports, and actionable insights."][i]}</p><a href="/contact">Let&apos;s talk <ArrowUpRight size={16} /></a></article>)}</section><section className="process section"><div><p className="eyebrow orange">How we work</p><h2>A clear process<br /><span>keeps good work moving.</span></h2></div><div className="process-list">{[["01", "Discover", "We understand your business, audience, objectives, and the outcome you want to achieve."], ["02", "Strategy", "We translate requirements into a clear creative or technical direction."], ["03", "Create", "We design, develop, write, analyze, and refine with the original objective in view."], ["04", "Refine", "We review carefully, improve with feedback, and make the experience ready for use."], ["05", "Deliver", "We prepare the final files, assets, documentation, or digital product for the next stage."]].map(([num, title, copy]) => <div className="process-item" key={num}><span>{num}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></section></Layout>; }

export function PortfolioPage() { const [filter, setFilter] = useState("All"); const categories = ["All", "Branding", "Web", "Shopify", "Publishing", "Content", "Analytics"]; const visible = filter === "All" ? projects : projects.filter((p) => p.category === filter); return <Layout><PageIntro kicker="Portfolio" title={<>Selected concept <span>work.</span></>} text="A growing collection of realistic sample projects across identity, digital experiences, publishing, content, and analytics. Each entry is presented as sample work while the studio portfolio grows." /><section className="portfolio section"><div className="filter-bar" role="tablist">{categories.map((cat) => <button className={filter === cat ? "active" : ""} onClick={() => setFilter(cat)} key={cat} role="tab" aria-selected={filter === cat}>{cat}</button>)}</div><div className="portfolio-grid">{visible.map((project) => <ProjectCard project={project} key={project.id} />)}</div></section></Layout>; }

export function CaseStudiesPage() { return <Layout><PageIntro kicker="Case studies" title={<>Behind the <span>finished frame.</span></>} text="A closer look at how strategy, design, and technology come together. These are realistic sample studies created to show the kind of thinking, craft, and practical direction Marvellous Studio brings to a project." /><section className="case-study section"><div className="case-study-hero"><img src="/manus-storage/mara-project-digital_42683e30.jpg" alt="Velora Shopify redesign concept" /><div><span className="concept-badge">Sample project</span><p className="eyebrow orange">E-commerce · Shopify · UX</p><h2>VELORA</h2><p>Shopify Store Redesign</p></div></div><div className="case-study-body"><div className="case-sidebar"><p className="eyebrow">Project details</p><p>Project type<br /><b>E-commerce</b></p><p>Services<br /><b>Shopify design · UX · store redesign</b></p><p>Status<br /><b>Sample project</b></p></div><div className="case-sections">{[["The challenge", "The original store concept lacked a consistent visual system and did not provide a particularly clear path for customers to explore products. The redesign needed to create a stronger first impression while making the shopping experience easier to navigate."], ["The approach", "We developed a cleaner visual hierarchy, simplified the navigation structure, strengthened product presentation, and created responsive layouts designed to maintain the experience across desktop and mobile devices."], ["The solution", "The redesigned storefront combines stronger branding with a more structured shopping journey. Product categories are easier to discover, important information receives greater visual emphasis, and calls to action are positioned more intentionally."], ["The outcome", "The final concept provides a more cohesive and professional e-commerce experience, demonstrating how strategic design can improve the way customers interact with an online store."]].map(([title, copy]) => <div key={title}><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section><section className="build-section"><p className="eyebrow orange">What we build</p><h2>Thoughtful creative work for businesses, brands, authors, and entrepreneurs.</h2><Button href="/contact">Start a project</Button></section></Layout>; }

const priceGroups = [
  { service: "Branding", note: "Identity systems for individuals, businesses, and growing brands.", packages: [["Basic", "₦75,000+", "Essential Brand Starter", "Primary logo, secondary variation, basic color palette, typography selection, simple brand direction, two revision rounds."], ["Standard", "₦180,000+", "Complete Brand Identity", "Everything in Basic, logo mark, color and typography systems, brand elements, business card, social assets, and mini guidelines."], ["Premium", "₦350,000+", "Strategic Brand Experience", "Everything in Standard, brand strategy direction, extended identity, guidelines, social templates, collateral, and creative direction."]] },
  { service: "Web Design & Development", note: "Responsive digital experiences designed around clarity, trust, and action.", packages: [["Basic", "₦150,000+", "Essential Website", "Up to four pages, responsive design, contact section, basic SEO, social integration, interactions, and deployment assistance."], ["Standard", "₦300,000+", "Business Website", "Up to seven pages, custom UI/UX, forms, analytics, blog or portfolio functionality, custom interactions, optimization, and post-launch support."], ["Premium", "₦600,000+", "Advanced Digital Experience", "Custom architecture, up to twelve pages, advanced UI/UX, CMS, integrations, advanced forms, SEO structure, analytics, and extended support."]] },
  { service: "Shopify & E-commerce", note: "Store experiences that make products easier to discover, trust, and buy.", packages: [["Basic", "₦200,000+", "Shopify Starter", "Shopify setup, theme configuration, homepage customization, product and category setup, essential pages, and mobile optimization."], ["Standard", "₦400,000+", "E-commerce Growth", "Everything in Basic, custom storefront design, improved product pages, navigation, conversion-focused layout, apps, SEO, and analytics."], ["Premium", "₦750,000+", "Custom Shopify Experience", "Everything in Standard, advanced customization, custom sections, product-page experience, integrations, analytics, optimization, and priority support."]] },
  { service: "Book Writing / Editing / Publishing", note: "Support for authors, entrepreneurs, educators, and organizations from manuscript to publication-ready files.", packages: [["Basic", "₦100,000+", "Book Starter", "Manuscript review, basic editing and proofreading, structure review, simple interior formatting, and publishing preparation guidance. Up to 10,000 words."], ["Standard", "₦250,000+", "Book Development", "Manuscript editing, structural review, proofreading, interior formatting, book layout, basic cover design, eBook formatting, and publishing-ready files. Up to 30,000 words."], ["Premium", "₦500,000+", "Complete Book Project", "Planning, writing or ghostwriting support, developmental editing, copy editing, proofreading, cover and interior design, eBook and print formatting, and KDP preparation. Up to 50,000 words."]] },
  { service: "Content & Copywriting", note: "Clear, persuasive words that support the brand and move readers toward action.", packages: [["Basic", "₦50,000+", "Content Starter", "Website copy for up to three pages, basic brand messaging, five social captions, and one revision round."], ["Standard", "₦120,000+", "Content Growth", "Website copy up to seven pages, brand messaging, ten social captions, three product or service descriptions, two articles, and two revision rounds."], ["Premium", "₦250,000+", "Complete Content System", "Full website copy, brand messaging, landing-page copy, product descriptions, articles, social content, CTAs, and content strategy direction."]] },
  { service: "Data Analytics", note: "Dashboards and reports that turn complex information into useful next steps.", packages: [["Basic", "₦100,000+", "Data Starter", "Data cleaning, basic analysis, descriptive statistics, basic charts, and a summary report."], ["Standard", "₦250,000+", "Business Insights", "Exploratory analysis, KPI development, visualization, interactive dashboard, insight report, and recommendations."], ["Premium", "₦500,000+", "Analytics & Intelligence", "Advanced cleaning, multiple data sources, advanced analysis, dashboard, KPI framework, trend analysis, executive summary, and documentation."]] },
];

export function PricingPage() { return <Layout><PageIntro kicker="Services & pricing" title={<>Clear scope for work that deserves to <span>move.</span></>} text="Starting-from prices give you a useful place to begin. Final pricing depends on scope, complexity, revisions, content, integrations, and timeline. International clients can request a USD or other-currency quote." /><section className="pricing section">{priceGroups.map((group) => <div className="price-group" key={group.service}><div className="price-group-head"><p className="eyebrow orange">{group.service}</p><p>{group.note}</p></div><div className="price-cards">{group.packages.map(([tier, price, title, details]) => <article className={`price-card ${tier === "Standard" ? "featured" : ""}`} key={tier}><div className="price-card-top"><span>{tier}</span>{tier === "Standard" && <b>Most requested</b>}</div><strong>{price}</strong><h3>{title}</h3><p>{details}</p><a href="/contact">Start a project <ArrowUpRight size={15} /></a></article>)}</div></div>)}</section><section className="custom-quote"><p className="eyebrow orange">Need something beyond the packages?</p><h2>Every project is different. Let&apos;s create a custom scope around your <span>goals.</span></h2><Button href="/contact">Request a custom quote</Button><small>Shopify subscriptions, paid themes, premium apps, domains, payment-provider charges, and other third-party costs are separate from the service fee.</small></section></Layout>; }

export function TestimonialsPage() { return <Layout><PageIntro kicker="Client stories" title={<>Good work leaves a <span>clearer trail.</span></>} text="We are currently building a collection of client experiences and project results. In the meantime, explore selected work or tell us what you are looking to build." /><section className="testimonials-empty section"><div className="empty-mark">“</div><p className="eyebrow orange">Client stories coming soon</p><h2>Real words from real clients will live here.</h2><p>When client-approved feedback is available, this page will become a home for the people and teams behind the work. Until then, the studio is focused on making the work itself speak clearly.</p><div><Button href="/portfolio">View our work</Button><Button href="/contact" secondary>Tell us what to build</Button></div></section></Layout>; }

export function ContactPageV2() { const [sent, setSent] = useState(false); return <Layout><PageIntro kicker="Contact" title={<>Have an idea? <span>Let&apos;s build it.</span></>} text="Whether you need a new brand identity, website, Shopify store, publication, content solution, or data dashboard, Marvellous Studio is ready to help." /><section className="contact-grid section"><div className="contact-main"><p className="eyebrow orange">Start a project</p><h2>Tell us what you&apos;re<br /><span>thinking about.</span></h2><p>Send a note with a little about your project, where you are in the process, and what a useful outcome looks like.</p><a className="button whatsapp-button" href={whatsapp} target="_blank" rel="noreferrer">Message on WhatsApp <ArrowUpRight size={17} /></a><div className="contact-details compact"><div><span className="eyebrow">Email</span><a href={`mailto:${email}`}>{email}</a></div><div><span className="eyebrow">WhatsApp</span><a href={whatsapp} target="_blank" rel="noreferrer">+234 806 625 3861 ↗</a></div></div></div><form className="inquiry-form" onSubmit={(e) => { e.preventDefault(); setSent(true); }}><div className="form-row"><label>Your name *<input required name="name" /></label><label>Email *<input required type="email" name="email" /></label></div><div className="form-row"><label>Company / brand<input name="company" /></label><label>WhatsApp / phone<input name="phone" /></label></div><div className="form-row"><label>What do you need? *<select required name="service"><option value="">Select a service</option><option>Branding</option><option>Web design & development</option><option>Shopify</option><option>Book writing / editing / publishing</option><option>Content / copywriting</option><option>Data analytics</option><option>Multiple services</option></select></label><label>Package interest<select name="package"><option>Basic</option><option>Standard</option><option>Premium</option><option>Custom / Not sure</option></select></label></div><div className="form-row"><label>Estimated budget<select name="budget"><option>Under ₦100k</option><option>₦100k–₦250k</option><option>₦250k–₦500k</option><option>₦500k+</option><option>Not sure yet</option></select></label><label>Desired timeline<input name="timeline" placeholder="e.g. 4–6 weeks" /></label></div><label>Tell us about your project *<textarea required name="message" rows={6} placeholder="What are you hoping to create, improve, or publish?" /></label><label>Project links / references<input name="links" placeholder="Optional" /></label><button className="button" type="submit">{sent ? "Inquiry noted" : "Submit project inquiry"} <ArrowUpRight size={16} /></button>{sent && <p className="form-success"><Check size={16} /> Your inquiry is prepared. Connect through WhatsApp or email to send it directly.</p>}</form></section></Layout>; }

export function ContactPage() { return <Layout><PageIntro kicker="Contact" title={<>Have an idea? <span>Let&apos;s build it.</span></>} text="Whether you need a new brand identity, website, Shopify store, publication, content solution, or data dashboard, Marvellous Studio is ready to help." /><section className="contact-grid section"><div className="contact-main"><p className="eyebrow orange">Start a project</p><h2>Tell us what you&apos;re<br /><span>thinking about.</span></h2><p>Send a note with a little about your project, where you are in the process, and what a useful outcome looks like. We&apos;ll take it from there.</p><a className="button whatsapp-button" href={whatsapp} target="_blank" rel="noreferrer">Message on WhatsApp <ArrowUpRight size={17} /></a></div><div className="contact-details"><div><span className="eyebrow">Email</span><a href={`mailto:${email}`}>{email}</a></div><div><span className="eyebrow">WhatsApp</span><a href={whatsapp} target="_blank" rel="noreferrer">+234 806 625 3861 ↗</a></div><div><span className="eyebrow">Socials</span><p>LinkedIn · Instagram · Behance</p><small>Links coming soon</small></div></div></section></Layout>; }
