// Marvellous Studio visual system: dark creative-tech surfaces, orange signal color, geometric spacing, and studio-first voice.
import { useState } from "react";
import { ArrowRight, ArrowUpRight, Check, ChevronDown, Menu, X } from "lucide-react";

export const logo = "/manus-storage/marvellous-studio-logo_c13ac32e.png";
export const whatsapp = "https://wa.me/2348066253861";
export const email = "primemarvel498@gmail.com";

export const projects = [
  { id: "aurelia", name: "AURELIA", category: "Branding", type: "Brand Identity & Art Direction", description: "A complete visual identity concept for a modern lifestyle brand seeking a sophisticated and recognizable presence.", services: "Branding · Art Direction · Graphic Design", tone: "coral", image: "/manus-storage/mara-project-identity_090146d4.jpg" },
  { id: "north", name: "NORTH & CO.", category: "Web", type: "E-commerce Website Experience", description: "A modern e-commerce website concept designed around a clean customer journey and strong product presentation.", services: "Web Design · UI/UX · Development", tone: "blue", image: "/manus-storage/mara-project-digital_42683e30.jpg" },
  { id: "velora", name: "VELORA", category: "Shopify", type: "Shopify Store Redesign", description: "A complete Shopify redesign concept created to transform an outdated online store into a cleaner, more engaging shopping experience.", services: "Shopify · E-commerce Design · UX", tone: "orange", image: "/manus-storage/mara-project-identity_090146d4.jpg" },
  { id: "creative", name: "THE CREATIVE MIND", category: "Publishing", type: "Book Design & Publishing", description: "A complete publishing concept for a professional nonfiction book, covering the visual direction from cover to interior pages.", services: "Book Design · Typesetting · KDP Formatting", tone: "purple", image: "/manus-storage/mara-editorial-hero_f8fe00e3.jpg" },
  { id: "insight", name: "INSIGHT 360", category: "Analytics", type: "Business Analytics Dashboard", description: "An interactive business intelligence concept designed to turn complex business information into an accessible visual reporting experience.", services: "Data Analytics · Data Visualization · Dashboard Design", tone: "green", image: "/manus-storage/mara-project-digital_42683e30.jpg" },
  { id: "lumen", name: "LUMEN", category: "Content", type: "Digital Brand & Website", description: "A complete digital presence concept bringing together brand identity, website design, and strategic content.", services: "Branding · Web Design · Copywriting", tone: "yellow", image: "/manus-storage/mara-editorial-hero_f8fe00e3.jpg" },
];

function Header() {
  const [open, setOpen] = useState(false);
  const links = [["Home", "/"], ["About", "/about"], ["Services", "/services"], ["Portfolio", "/portfolio"], ["Case Studies", "/case-studies"], ["Contact", "/contact"]];
  return <header className="site-header"><a className="brand-lockup" href="/"><img src={logo} alt="Marvellous Studio" /></a><nav className={open ? "main-nav open" : "main-nav"}>{links.map(([label, href]) => <a href={href} key={href} onClick={() => setOpen(false)}>{label}</a>)}<a className="nav-cta" href="/contact">Start a project <ArrowUpRight size={15} /></a></nav><button className="menu-toggle" onClick={() => setOpen(!open)} aria-label={open ? "Close menu" : "Open menu"}>{open ? <X /> : <Menu />}</button></header>;
}

function Footer() { return <footer className="footer"><div><a className="footer-logo" href="/"><img src={logo} alt="Marvellous Studio" /></a><p>Creative design, digital experiences,<br />and practical solutions for moving forward.</p></div><div className="footer-links"><span className="eyebrow">Explore</span><a href="/portfolio">Portfolio</a><a href="/services">Services</a><a href="/about">About the studio</a></div><div className="footer-links"><span className="eyebrow">Say hello</span><a href={`mailto:${email}`}>{email}</a><a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp ↗</a></div><div className="footer-base"><span>© 2025 Marvellous Studio</span><span>Founded by Odola Temidayo Marvellous</span><a href="#top">Back to top ↑</a></div></footer>; }

function Layout({ children }: { children: React.ReactNode }) { return <div className="app-shell" id="top"><Header />{children}<Footer /></div>; }
function PageIntro({ kicker, title, text }: { kicker: string; title: React.ReactNode; text: string }) { return <section className="page-intro"><p className="eyebrow orange">{kicker}</p><h1>{title}</h1><p className="page-intro-text">{text}</p></section>; }
function Button({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) { return <a className={secondary ? "button button-secondary" : "button"} href={href}>{children}<ArrowUpRight size={16} /></a>; }

export function HomePage() { return <Layout><section className="home-hero"><div className="hero-content"><div className="hero-kicker"><span className="signal-dot" /> Premium creative digital studio</div><h1>We design brands, digital experiences, and solutions that <span>move businesses forward.</span></h1><p>Marvellous Studio combines graphic design, branding, web development, Shopify, publishing, content, and data analytics to help turn ideas into professional digital experiences.</p><div className="hero-buttons"><Button href="/portfolio">View our work</Button><Button href="/contact" secondary>Start a project</Button></div><div className="hero-trust">Branding <i>·</i> Web <i>·</i> Shopify <i>·</i> Publishing <i>·</i> Content <i>·</i> Analytics</div></div><div className="hero-visual"><img src="/manus-storage/mara-editorial-hero_f8fe00e3.jpg" alt="Creative studio materials arranged on a desk" /><div className="hero-visual-tag">Make it<br /><b>marvellous.</b></div><div className="hero-visual-index">01 <span>/</span> 06</div></div></section><section className="home-work section"><div className="section-top"><div><p className="eyebrow">01 / Selected work</p><h2>Built around strategy,<br /><span>creativity, and function.</span></h2></div><a className="arrow-link" href="/portfolio">See all work <ArrowRight size={18} /></a></div><div className="featured-grid">{projects.slice(0, 3).map((project) => <ProjectCard project={project} key={project.id} />)}</div></section><section className="home-statement"><p className="eyebrow orange">A multidisciplinary studio</p><h2>More than design. We build the pieces that make a business look, communicate, and <span>perform better.</span></h2><Button href="/about" secondary>Meet the studio</Button></section><section className="home-services section"><div className="section-top"><div><p className="eyebrow">02 / What we do</p><h2>One studio.<br /><span>Many ways forward.</span></h2></div><a className="arrow-link" href="/services">Explore services <ArrowRight size={18} /></a></div><div className="service-preview">{["Brand & Graphic Design", "Web Design & Development", "Shopify & E-commerce", "Book Writing & Publishing", "Copywriting & Content", "Data Analytics"].map((name, i) => <a href="/services" key={name}><span>0{i + 1}</span><strong>{name}</strong><ArrowUpRight size={17} /></a>)}</div></section><section className="home-cta"><p className="eyebrow">03 / Start a conversation</p><h2>Have an idea?<br /><span>Let&apos;s build it.</span></h2><Button href="/contact">Start a project</Button></section></Layout>; }

function ProjectCard({ project }: { project: typeof projects[number] }) { return <a className={`project-card tone-${project.tone}`} href={project.id === "velora" ? "/case-studies" : "/portfolio"}><div className="project-image"><img src={project.image} alt={`${project.name} concept project`} /><span className="concept-badge">Concept project</span><span className="project-open"><ArrowUpRight size={19} /></span></div><div className="project-card-meta"><span>{project.category}</span><h3>{project.name}</h3><p>{project.type}</p></div></a>; }

export function AboutPage() { return <Layout><PageIntro kicker="About the studio" title={<>Built for ideas that deserve to <span>move.</span></>} text="Marvellous Studio is a multidisciplinary creative digital studio focused on helping businesses, entrepreneurs, authors, and growing brands bring their ideas to life." /><section className="about-grid section"><div className="about-lead"><p className="eyebrow orange">The thinking behind the work</p><h2>Good design should not only look good. <span>It should have a purpose.</span></h2></div><div className="about-copy"><p>Marvellous Studio brings together creative design, branding, web design and development, Shopify e-commerce, copywriting, book writing and publishing, and data analytics to create solutions that are both visually engaging and useful.</p><p>Rather than treating each project as an isolated task, we look at the bigger picture — how the brand communicates, how customers experience it, and how the final product supports the client&apos;s goals.</p><div className="founder-card"><p className="eyebrow">Behind the studio</p><h3>Odola Temidayo Marvellous</h3><p>Founder & Creative Director</p><div className="founder-line" /><p>Odola helps businesses turn ideas into strong brands, digital experiences, content, and practical digital solutions.</p></div></div></section><section className="audience-band"><p className="eyebrow orange">Who we work with</p><div className="audience-list"><span>Entrepreneurs</span><span>Startups</span><span>Growing businesses</span><span>E-commerce brands</span><span>Organizations</span><span>Book authors</span></div></section></Layout>; }

export function ServicesPage() { const items = ["Brand & Graphic Design", "Web Design & Development", "Shopify & E-commerce", "Book Writing & Publishing", "Copywriting & Content", "Data Analytics"]; return <Layout><PageIntro kicker="Services" title={<>The right mix of <span>creative and practical.</span></>} text="From a first visual identity to a high-converting store or a publication ready for readers, we build the pieces that help your work travel further." /><section className="services-grid section">{items.map((name, i) => <article className="service-card" key={name}><span className="service-index">0{i + 1}</span><h2>{name}</h2><p>{["We create visual identities and communication materials that give businesses a recognizable and professional presence.", "We design responsive websites that combine strong visual presentation with intuitive navigation and functional user experiences.", "We create and redesign Shopify stores with a focus on presentation, usability, mobile responsiveness, and the customer journey.", "We help authors, entrepreneurs, educators, and organizations transform ideas into polished publications for digital and print.", "We develop clear and persuasive content that helps businesses communicate their value across every important touchpoint.", "We turn complex information into clear dashboards, visual reports, and actionable insights."][i]}</p><a href="/contact">Let&apos;s talk <ArrowUpRight size={16} /></a></article>)}</section><section className="process section"><div><p className="eyebrow orange">How we work</p><h2>A clear process<br /><span>keeps good work moving.</span></h2></div><div className="process-list">{[["01", "Discover", "We understand your business, audience, objectives, and the outcome you want to achieve."], ["02", "Strategy", "We translate requirements into a clear creative or technical direction."], ["03", "Create", "We design, develop, write, analyze, and refine with the original objective in view."], ["04", "Refine", "We review carefully, improve with feedback, and make the experience ready for use."], ["05", "Deliver", "We prepare the final files, assets, documentation, or digital product for the next stage."]].map(([num, title, copy]) => <div className="process-item" key={num}><span>{num}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></section></Layout>; }

export function PortfolioPage() { const [filter, setFilter] = useState("All"); const categories = ["All", "Branding", "Web", "Shopify", "Publishing", "Content", "Analytics"]; const visible = filter === "All" ? projects : projects.filter((p) => p.category === filter); return <Layout><PageIntro kicker="Portfolio" title={<>Selected concept <span>work.</span></>} text="A growing collection of concept projects across identity, digital experiences, publishing, content, and analytics. Every project is labeled clearly while the studio portfolio grows." /><section className="portfolio section"><div className="filter-bar" role="tablist">{categories.map((cat) => <button className={filter === cat ? "active" : ""} onClick={() => setFilter(cat)} key={cat} role="tab" aria-selected={filter === cat}>{cat}</button>)}</div><div className="portfolio-grid">{visible.map((project) => <ProjectCard project={project} key={project.id} />)}</div></section></Layout>; }

export function CaseStudiesPage() { return <Layout><PageIntro kicker="Case studies" title={<>Behind the <span>finished frame.</span></>} text="A closer look at how strategy, design, and technology come together. These are concept studies created to show the kind of thinking Marvellous Studio brings to a project." /><section className="case-study section"><div className="case-study-hero"><img src="/manus-storage/mara-project-digital_42683e30.jpg" alt="Velora Shopify redesign concept" /><div><span className="concept-badge">Concept project</span><p className="eyebrow orange">E-commerce · Shopify · UX</p><h2>VELORA</h2><p>Shopify Store Redesign</p></div></div><div className="case-study-body"><div className="case-sidebar"><p className="eyebrow">Project details</p><p>Project type<br /><b>E-commerce</b></p><p>Services<br /><b>Shopify design · UX · store redesign</b></p><p>Status<br /><b>Concept project</b></p></div><div className="case-sections">{[["The challenge", "The original store concept lacked a consistent visual system and did not provide a particularly clear path for customers to explore products. The redesign needed to create a stronger first impression while making the shopping experience easier to navigate."], ["The approach", "We developed a cleaner visual hierarchy, simplified the navigation structure, strengthened product presentation, and created responsive layouts designed to maintain the experience across desktop and mobile devices."], ["The solution", "The redesigned storefront combines stronger branding with a more structured shopping journey. Product categories are easier to discover, important information receives greater visual emphasis, and calls to action are positioned more intentionally."], ["The outcome", "The final concept provides a more cohesive and professional e-commerce experience, demonstrating how strategic design can improve the way customers interact with an online store."]].map(([title, copy]) => <div key={title}><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section><section className="build-section"><p className="eyebrow orange">What we build</p><h2>Thoughtful creative work for businesses, brands, authors, and entrepreneurs.</h2><Button href="/contact">Start a project</Button></section></Layout>; }

export function ContactPage() { return <Layout><PageIntro kicker="Contact" title={<>Have an idea? <span>Let&apos;s build it.</span></>} text="Whether you need a new brand identity, website, Shopify store, publication, content solution, or data dashboard, Marvellous Studio is ready to help." /><section className="contact-grid section"><div className="contact-main"><p className="eyebrow orange">Start a project</p><h2>Tell us what you&apos;re<br /><span>thinking about.</span></h2><p>Send a note with a little about your project, where you are in the process, and what a useful outcome looks like. We&apos;ll take it from there.</p><a className="button whatsapp-button" href={whatsapp} target="_blank" rel="noreferrer">Message on WhatsApp <ArrowUpRight size={17} /></a></div><div className="contact-details"><div><span className="eyebrow">Email</span><a href={`mailto:${email}`}>{email}</a></div><div><span className="eyebrow">WhatsApp</span><a href={whatsapp} target="_blank" rel="noreferrer">+234 806 625 3861 ↗</a></div><div><span className="eyebrow">Socials</span><p>LinkedIn · Instagram · Behance</p><small>Links coming soon</small></div></div></section></Layout>; }
